# Generated by Django 4.2.7 on 2023-11-29 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 15, 26, 4, 609500, tzinfo=datetime.timezone.utc)),
        ),
    ]
