# Generated by Django 4.2.7 on 2023-12-01 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 6, 52, 33, 60686, tzinfo=datetime.timezone.utc)),
        ),
    ]
