# Generated by Django 4.2.7 on 2023-12-01 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 2, 46, 989980, tzinfo=datetime.timezone.utc)),
        ),
    ]
