# Generated by Django 4.2.7 on 2023-12-04 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 11, 13, 10, 143236, tzinfo=datetime.timezone.utc)),
        ),
    ]
