# Generated by Django 4.2.7 on 2023-12-06 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=212)),
                ('last_name', models.CharField(max_length=212)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
                ('profession', models.CharField(max_length=212)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 15, 14, 47, 312877, tzinfo=datetime.timezone.utc)),
        ),
    ]
